PRODUCT_VERSION_MAJOR = 21
PRODUCT_VERSION_MINOR = 0

ifeq ($(CYGNUS_VERSION_APPEND_TIME_OF_DAY),true)
    CYGNUS_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    CYGNUS_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set CYGNUS_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef CYGNUS_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "CYGNUS_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^CYGNUS_||g')
        CYGNUS_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(CYGNUS_BUILDTYPE)),)
    CYGNUS_BUILDTYPE := UNOFFICIAL
    CYGNUS_EXTRAVERSION :=
endif

ifeq ($(CYGNUS_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        CYGNUS_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

CYGNUS_VERSION_SUFFIX := $(CYGNUS_BUILD_DATE)-$(CYGNUS_BUILDTYPE)$(CYGNUS_EXTRAVERSION)-$(CYGNUS_BUILD)

# Internal version
CYGNUS_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CYGNUS_VERSION_SUFFIX)

# Display version
CYGNUS_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(CYGNUS_VERSION_SUFFIX)
